version: '2'
services:
  mongodata:
    image: mongo:3.2
    volumes:
      - /data/db
    entrypoint: /bin/bash
  mongo:
    image: mongo:3.2
    depends_on:
      - mongodata
    volumes_from:
      - mongodata
    ports:
      #kh: only specify internal port, not external, so we can scale with docker-compose scale
      - "27017"
  myRetail:
    image: myretail
    depends_on:
      - mongo
    environment:
      - MONGODB_DB_NAME=retail
    ports:
      - 9898:9898
    links:
      - mongo
